version: '3.8'

services:
  auth_microservice:
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_DATABASE: auth_module
      MYSQL_USER: user
      MYSQL_PASSWORD: secret_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network
    # Добавьте эти параметры:
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret_password"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge